---
title: "OCC CVcurrent"
author: "M. Snyder"
date: "May 14, 2019"
output: html_document
editor_options: 
  chunk_output_type: console
chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
```

```{r import abundance, echo=FALSE}
OC_COHO_ABUNDANCE <- read.csv("D:/Resiliency/Marcia/Data/Coho_Abundance/OC_COHO_ABUNDANCE.csv")
AbundanceGroups <- read.csv("D:/Resiliency/Matt's Work/Data/Spreadsheets/AbundanceGroups.csv")
```


```{r subset and transform, echo=FALSE}
#names(OC_COHO_ABUNDANCE)
# drop unnecessary columns
columns_for_keep<-c("Year","Alsea","Beaver","Coos","Coquille", "Floras","Lower.Umpqua","Middle.Umpqua","Necanicum","Nehalem","Nestucca"     
, "North.Umpqua","Salmon","Siletz","Siltcoos","Siuslaw","Sixes"        
, "South.Umpqua","Tahkenitch","Tenmile","Tillamook","Yaquina")
abundance<-dplyr::select(OC_COHO_ABUNDANCE, one_of(columns_for_keep))
# drop years before 1994
abundance<-abundance[which(abundance$Year >1993),]
# drop year column
abundance<-abundance[,-1]
# ln(x+1) transform
# transform abundance column subset
#abundance.plus.1<-abundance # create copy of abundance df
#abundance.plus.1[,2:22]<-abundance[,2:22] + 1 # add 1
#abundance.log<-abundance.plus.1 # create copy of abundance plus 1 df
#abundance.log<-log(abundance.plus.1[,2:22]) # natural log transform df
```


```{r CVcurrent, eval=TRUE, echo=FALSE}
#### calculate denomenator of CVcurrent ####
# mean per population from 1994-2016
pop_means<-colMeans(abundance)
# sum mean per population
sum_mean_pops<-sum(pop_means)

#### calculate numerator of CVcurrent ####
# calculate variance per population, 2 represents axis(columns)
pop_variance<-apply(abundance,2,var)
# get total esu variance
esu_var_total<-sum(pop_variance)
# function to convert covariance from sample (n-1) to population(n)
cov.pop <- function(x,y=NULL) {
   cov(x,y)*(NROW(x)-1)/NROW(x)
}
# 
# calculate covariance matrix
cov.mat<-cov.pop(abundance)

# calculate sum of covariances
sum_cov<-NULL
temp_sum_temp<-NULL
for (i in 1:(length(pop_variance)-1)){
  temp_sum<-sum(cov.mat[i,(i+1):dim(cov.mat)[2]])
  temp_sum_temp[i]<-temp_sum 
  sum_cov<-sum(temp_sum_temp)
}

# calculate CVcurrent
CVcurrent<-( sqrt(esu_var_total + sum_cov) ) / sum_mean_pops


```



```{r define CVcurrent loo function, echo=FALSE}
CVcurrent_loo<-function(df){
  #### calculate denomenator of CVcurrent ####
# mean per population from 1994-2016
pop_means<-colMeans(df)
# sum mean per population
sum_mean_pops<-sum(pop_means)

#### calculate numerator of CVcurrent ####
# calculate variance per population, 2 represents axis(columns)
pop_variance<-apply(df,2,var)
# get total esu variance
esu_var_total<-sum(pop_variance)
# function to convert covariance from sample (n-1) to population(n)
cov.pop <- function(x,y=NULL) {
   cov(x,y)*(NROW(x)-1)/NROW(x)
}
# 
# calculate covariance matrix
cov.mat<-cov.pop(df)

# calculate sum of covariances
sum_cov<-NULL
temp_sum_temp<-NULL
for (i in 1:(length(pop_variance)-1)){
  temp_sum<-sum(cov.mat[i,(i+1):dim(cov.mat)[2]])
  temp_sum_temp[i]<-temp_sum 
  sum_cov<-sum(temp_sum_temp)
}

# calculate CVcurrent
CVcurrent<-( sqrt(esu_var_total + sum_cov) ) / sum_mean_pops
}

```

```{r calculate CVcurrent_loo, eval=TRUE, echo=FALSE}

CVcurrent_LOO_V<-NULL # set up empty vector for results
no.populations<-dim(abundance)[2]
# calculate sharpe ratio for all populations minus 1
for (i in 1:no.populations){
  temp_df<-abundance[,-i]
  temp_out<-CVcurrent_loo(temp_df)
  CVcurrent_LOO_V[i]<-temp_out
}
# combine Sharpe ratio with population left out
pops_names<-colnames(abundance) 
CVcurrent_df<-data.frame(pops_names, CVcurrent_LOO_V)
```


```{r calculate CVcurrent without lakes, echo=FALSE}
# drop lakes from dataframe
abundance2<-dplyr::select(abundance, -Tahkenitch, -Tenmile, -Siltcoos)
# create empty vector for results
CVcurrent_LOO_V_lakes<-NULL
no.populations<-dim(abundance2)[2] 
#temp<-colnames(abundance.log)
for (i in 1:no.populations){
  temp_df<-abundance2[,-i]
  temp_out<-CVcurrent_loo(temp_df)
  CVcurrent_LOO_V_lakes[i]<-temp_out
}
# get population names
pops_names<-colnames(abundance2)
CVcurrent_no_lakes<-data.frame(pops_names, CVcurrent_LOO_V_lakes)

```



```{r combine results CVcurrent, echo=FALSE}
#names(CVcurrent_df)
#names(CVcurrent_no_lakes)
all_CVcurrent<-merge(CVcurrent_df, CVcurrent_no_lakes, by.x="pops_names", by.y="pops_names", all.x = TRUE)
```

```{r get stratum for plot CVcurrent, echo=FALSE}
all_CVcurrent_stratum<-merge(all_CVcurrent, AbundanceGroups, by.x="pops_names", by.y="Population")

```


```{r plot all CVcurrent, echo=FALSE, warning=FALSE}

all<-ggplot(data=all_CVcurrent_stratum, aes(pops_names, CVcurrent_LOO_V, colour=Stratum)) +geom_point(size=3)
all + labs(title=" ", x="Population", y="CV current") +
  theme(axis.text.x=element_text(angle=90))
```


```{r plot CVcurrent vs. CVcurrent, echo=FALSE, warning=FALSE}

apr<-ggplot(data=all_CVcurrent_stratum,
            aes(x=CVcurrent_LOO_V, y=CVcurrent_LOO_V_lakes, colour=Stratum)) +
    geom_point(size=3)
apr + labs(title="CV current comparison without lake populations", x="CV current", y="CV current w/o Lakes")

```

```{r write sharpe csv, echo=FALSE}
write.csv(all_CVcurrent_stratum, "D:/Resiliency/Marcia/Data/Portfolio_metrics/all_CVcurrent_stratum.csv")
```



```{r sharpe ratio, eval=FALSE, echo=FALSE}
#### Calculate numerator of sharpe ratio
# calculate total ESU production 1994-2016
esu_totals<-rowSums(abundance.log)
esu_total<-sum(esu_totals)
# calculate total population production 1994-2016
pop_totals<-colSums(abundance.log)
# calculate population proportional contribution
pop_contribution<-pop_totals / esu_total
# mean per population from 1994-2016
pop_means<-colMeans(abundance.log)
# calculate weighted individual return
weighted_returns<-pop_contribution * pop_means
# sum all individual weighted returns for Up (return part of Sharpe Ratio)
sharpe_return<-sum(weighted_returns)

#### calculate denominator of sharpe ratio
# calculate variance per population, 2 represents axis(columns)
pop_variance<-apply(abundance.log,2,var)
# calculate variance squared
#pop_variance2<-pop_variance * pop_variance
# pop variance weighted contribution
pop_var_contribution<-pop_contribution * pop_contribution * pop_variance
# get total esu variance
esu_var_total<-sum(pop_var_contribution)
# function to convert covariance from sample (n-1) to population(n)
cov.pop <- function(x,y=NULL) {
   cov(x,y)*(NROW(x)-1)/NROW(x)
}
# calculate covariance matrix
cov.mat<-cov.pop(abundance.log)
#cov.mat2<-cov(abundance.log, abundance.log)
#### TEST OUT COVARIANCE population vs. mean####
# COV<- function(x,y) {
#   if(length(x)!=length(y)) {stop('x must have the same length as y ')}
#   x.bar <- mean(x)
#   y.bar <- mean(y)
#   N <- length(x)
# 
#   Cov <- (sum((x-x.bar)*(y-y.bar))) / (N)
#   return(Cov)
# }
# COV(abundance.log$Alsea, abundance.log$Coos)

# loop to calculate weighted covariance contribution per pair
cov_weighted<-matrix(9999, nrow=length(pop_contribution), ncol = length(pop_contribution))
for (i in 1:length(pop_contribution)){
  for (j in 1:length(pop_contribution)){
    out_temp<-cov.mat[i,j]
    pair_temp<-out_temp * pop_contribution[i] * pop_contribution[j]
    cov_weighted[i,j] <- pair_temp
  }
}


## check weighted covariance contribution of each pair
#0.8795310 * 0.04932383 * 0.04369052
#cov_weighted[1,2]

# sum up weighted covariance
sum_cov<-NULL
temp_sum_temp<-NULL
for (i in 1:(length(pop_contribution)-1)){
  temp_sum<-sum(cov_weighted[i,(i+1):dim(cov_weighted)[2]])
  temp_sum_temp[i]<-temp_sum 
  sum_cov<-sum(temp_sum_temp)
}

#### calculate sharpe ratio
Sharpe_ratio<-sharpe_return / sqrt((esu_var_total + sum_cov))

```

```{r covar function, eval=FALSE, echo=FALSE}
# function to convert covariance from sample (n-1) to population(n)
cov.pop <- function(x,y=NULL) {
   cov(x,y)*(NROW(x)-1)/NROW(x)
}
```

```{r define sharpe loo function, eval=FALSE, echo=FALSE}
sharpes_loo<-function(df){
#### Calculate numerator of sharpe ratio
# calculate total ESU production 1994-2016
esu_totals<-rowSums(df)
esu_total<-sum(esu_totals)
# calculate total population production 1994-2016
pop_totals<-colSums(df)
# calculate population proportional contribution
pop_contribution<-pop_totals / esu_total
# mean per population from 1994-2016
pop_means<-colMeans(df)
# calculate weighted individual return
weighted_returns<-pop_contribution * pop_means
# sum all individual weighted returns for Up (return part of Sharpe Ratio)
sharpe_return<-sum(weighted_returns)

#### calculate denominator of sharpe ratio
pop_variance<-apply(df,2,var)
# calculate variance squared
#pop_variance2<-pop_variance * pop_variance
# pop variance weighted contribution
pop_var_contribution<-pop_contribution * pop_contribution * pop_variance
# get total esu variance
esu_var_total<-sum(pop_var_contribution)
# calculate covariance matrix
cov.mat<-cov.pop(df)
# loop to calculate weighted covariance contribution per pair
cov_weighted<-matrix(9999, nrow=length(pop_contribution), ncol = length(pop_contribution))
for (i in 1:length(pop_contribution)){
  for (j in 1:length(pop_contribution)){
    out_temp<-cov.mat[i,j]
    pair_temp<-out_temp * pop_contribution[i] * pop_contribution[j]
    cov_weighted[i,j] <- pair_temp
  }
}

## check weighted covariance contribution of each pair
#0.8795310 * 0.04932383 * 0.04369052
#cov_weighted[1,2]

# sum up weighted covariance
sum_cov<-NULL
temp_sum_temp<-NULL
for (i in 1:(length(pop_contribution)-1)){
  temp_sum<-sum(cov_weighted[i,(i+1):dim(cov_weighted)[2]])
  temp_sum_temp[i]<-temp_sum 
  sum_cov<-sum(temp_sum_temp)
}

#### calculate sharpe ratio
sharpe_ratio<-sharpe_return / sqrt((esu_var_total + sum_cov))
  return(sharpe_ratio)
}

```

```{r test sharpes loo function, eval=FALSE, include=FALSE, echo=FALSE}

sharpes_loo(abundance.log) # returns the same value
```


```{r calculate sharpes_loo, eval=FALSE, echo=FALSE}
SHARPES_LOO_V<-NULL # set up empty vector for results
no.populations<-dim(abundance.log)[2]
# calculate sharpe ratio for all populations minus 1
for (i in 1:no.populations){
  temp_df<-abundance.log[,-i]
  temp_out<-sharpes_loo(temp_df)
  SHARPES_LOO_V[i]<-temp_out
}
# combine Sharpe ratio with population left out
pops_names<-colnames(abundance.log) 
sharpes<-data.frame(pops_names, SHARPES_LOO_V)
```


```{r calculate sharpes_loo without lakes, echo=FALSE, eval=FALSE}
# drop lakes from dataframe
abundance.log2<-dplyr::select(abundance.log, -Tahkenitch, -Tenmile, -Siltcoos)
# create empty vector for results
SHARPES_LOO_V_lakes<-NULL
no.populations<-dim(abundance.log2)[2] 
#temp<-colnames(abundance.log)
for (i in 1:no.populations){
  temp_df<-abundance.log2[,-i]
  temp_out<-sharpes_loo(temp_df)
  SHARPES_LOO_V_lakes[i]<-temp_out
}
# get population names
pops_names<-colnames(abundance.log2)
sharpes_no_lakes<-data.frame(pops_names, SHARPES_LOO_V_lakes)

```


```{r combine results, echo=FALSE, eval=FALSE}
#names(sharpes)
#names(sharpes_no_lakes)
all_sharpe<-merge(sharpes, sharpes_no_lakes, by.x="pops_names", by.y="pops_names", all.x = TRUE)
```

```{r get stratum for plot, echo=FALSE, eval=FALSE}
all_sharpe_stratum<-merge(all_sharpe, AbundanceGroups, by.x="pops_names", by.y="Population")

```


```{r plot all Sharpe, echo=FALSE, eval=FALSE}
#plot(SHARPES_LOO_V_lakes~SHARPES_LOO_V, data=all_sharpe, pch=19, col="purple", cex=2, xlab="Sharpe Ratio Leave One Out", ylab="Sharpe Ratio w/o Lakes")
all<-ggplot(data=all_sharpe_stratum, aes(pops_names, SHARPES_LOO_V, colour=Stratum)) +geom_point(size=3)
all + labs(title="Sharpe Ratios", x="Population", y="Sharpe Ratio") +
  theme(axis.text.x=element_text(angle=90))
```


```{r plot sharpe vs. sharpe, echo=FALSE, eval=FALSE}
#plot(SHARPES_LOO_V_lakes~SHARPES_LOO_V, data=all_sharpe, pch=19, col="purple", cex=2, xlab="Sharpe Ratio Leave One Out", ylab="Sharpe Ratio w/o Lakes")

apr<-ggplot(data=all_sharpe_stratum,
            aes(x=SHARPES_LOO_V, y=SHARPES_LOO_V_lakes, colour=Stratum)) +
    geom_point(size=3)
apr + labs(title="Sharpe ratio comparison", x="Sharpe Ratio Leave One Out", y="Sharpe Ratio w/o Lakes")

```


```{r write sharpe csv, echo=FALSE, eval=FALSE}
write.csv(all_sharpe_stratum, "E:/Resiliency/Marcia/Data/Portfolio_metrics/all_sharpe_stratum.csv")
```


```{r calculate CV function, echo=FALSE, eval=FALSE}
CV <- function(x) {sd(x) / mean(x)}

```

```{r CV for populations (log +1), echo=FALSE, eval=FALSE}
# get CV for each population
CV_pops<-mapply(CV, abundance.log)
# calculate mean CV for total from mean of ind CV
CV_mean_ind<-mean(CV_pops)
# convert df of abundance to vector
abundance.log.v<-as.vector(as.matrix(abundance.log))
CV(abundance.log.v)
```


```{r CV for populations, echo=FALSE, eval=FALSE}
# drop year column
abundance<-dplyr::select(abundance, -Year)
# get CV for each population
CV_pops<-mapply(CV, abundance)
# calculate mean CV for total from mean of ind CV
CV_mean_ind<-mean(CV_pops)
CV_mean_ind
# convert df of abundance to vector
abundance.v<-as.vector(as.matrix(abundance))
CV_total<-CV(abundance.v)
# get population names
pops_names<-colnames(abundance)
CV_all<-data.frame(pops_names, CV_pops)
```


```{r get stratum for CV plot, echo=FALSE, eval=FALSE}
all_CV_stratum<-merge(CV_all, AbundanceGroups, by.x="pops_names", by.y="Population")

```


```{r CV no lakes, echo=FALSE, eval=FALSE}
# drop lakes from dataframe
abundance.lakes<-dplyr::select(abundance, -Tahkenitch, -Tenmile, -Siltcoos)
# get CV for each population
CV_pops_lakes<-mapply(CV, abundance.lakes)
# calculate mean CV for total from mean of ind CV
CV_mean_ind_lakes<-mean(CV_pops_lakes)
CV_mean_ind_lakes
# convert df of abundance to vector
abundance.v.lakes<-as.vector(as.matrix(abundance.lakes))
CV_total_lakes<-CV(abundance.v.lakes)
# get population names
pops_names<-colnames(abundance.lakes)
CV_all_lakes<-data.frame(pops_names, CV_pops_lakes)

# merge with CV and stratum
CV_out<-merge(all_CV_stratum, CV_all_lakes, by.x="pops_names", by.y="pops_names", all=TRUE)
```


```{r CV plot, echo=FALSE, eval=FALSE}
all<-ggplot(data=all_CV_stratum, aes(pops_names, CV_pops, colour=Stratum)) +geom_point(size=3)
all + labs(x="Population", y="CV") +
  theme(axis.text.x=element_text(angle=90))
```

